### ISSUE TITLE
not enough balls

### ISSUE THREAD

**Issue by pr1ncess-emily** [CIA-Puppygirl/poopballs#5]
moar bals please

**Comment by pr1ncess-emily** [comment]
running on Manjaro Linux kernel version 6.9.420

**Comment by CIA-Puppygirl** [comment]
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAJYAyAMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAADAAECBAUGB//EADsQAAIBAgQEAwYEBAUFAAAAAAECAAMRBBIhMQVBUWEGEyIycYGRobEHQsHRFCNS4RVykvDxJFNigsL/xAAbAQACAwEBAQAAAAAAAAAAAAAAAQMEBQYCB//EACURAAICAQQCAgMBAQAAAAAAAAABAgMRBAUhMRITIjIUQVGBBv/aAAwDAQACEQMRAD8A8wVIQJCIsIFgIEFkgsMqSWTtEAEJJhIUJ2kssABZY+WFy9o4TWAAcgjhIfJHKZUZzoqC7HoIm8DK+TtB1KlKj7dRVPc6wJq4vH1TR4fRqudstNSzH5bTsvA3gDF1cb/Hcewb06FIhqdGrvVflcdB9ZBfqK6YuUmNRyVuFeEMdxTCU8TSenRpPqvmqQSPdbaWavgPiC+ziMK3a5H6T1YYPTUn3DYRmwFM/l1nOS3m9yyuif1xPF8Z4Y4phUZ2wpqIu7UWzgfKY7U8psQQeh0nuuIwCjVVse04bxj4YxVdn4jw4tUqKL1cMbeoDcp37S/o929kvGzCPEq8co8/KXEYpDo6VFBAs3MHlEVm4iIqlYxWWCsgyWgIrMgg2SW8sgVgBSKQbKZdZIF0gBUZYoVhFADZVbQgWOFhAt4wIhZIJCBdI+WAyGQyWWFVTJZAYgAqkcJpDhNJJacBgqdJ3dUQEsxsABvPReDeGcIvDKmExaCoMSlq55n/AMR9JheEMB5uJOJqLpTNk9/X4CejYWiFVV3Cic5u2skpKqD6Ja48cjcK4ZhOH0BRwGEo4akPy00A+c0kpag6kjqZKknaWUSwmE3KbyyUCtO+wian2ha7ph6T1ajBURSzE9BObPjrw8ou2JcdzRb9pNDT2T+qyLKRsPR52lGvQ9QKjUayovjrw1UNv8RVSf6kcfpNZDTr0Er0XWpSqDMjrsRykc6bKvsmhppnlvjLwWDiX4jwbLSruxZ6Oyueduhv8DOKKOoK1abU3BsytoQeYM914tSvQv0nnvjLh48sY1FAZCA/cbftNzbdxk2qrOSOcF2jiiLSJFxLb0heBNPWdEQFcpIFLSyUPeDYQArssEyyyy3gnWAiq6xoZljxgayqYRV2AklWERL3gBBbX7woS9riSWnzkwWgMiFAkgBaSAJI6SSpcXiAhlMkqEiwkwsIAAbdNyYDOz8K0QmEp6a2zH7zscMoFp5ZxDxUfD9LAU8PTWq72esD/wBsW0Hc6/KelcIx2H4jgqOMwb56FVbqf9/acbr6bFL2tcNlmLXRs0pYG0BRtaHBvKteBsw/GD1DwlsNRvnxByG39O5/b4zy/jnBXwqWKET1XiFVk4irV1tQRPS52vznF+MMfRxBbK3q5m1gfcJ1221RhQmv2VrOzy/FqabnTaex/hfxD/EPCVOi7ZqmDdqTe691+hA+E8e4lVGdxvO3/BXE1hxLH4by6hoVKQfPb0q40se5B+kh3WtT07/qHU+T0fiaA0CJynG8MtfC1aL7VEK+686zihAS205njDrTos5IAVbknYAbmcvQ35rBZfR5ZSLPTGY3YaH4R2WNhnDviGpn0+c5UjoSYY6zuoZcVkpgSBBOgh2GsGwtPQFVk6QTraWzIOARGBRcCKFqU4oCNlVtCoJELsbXhFA6WjAQAklPSLISdDJpTI33iGIa8h8IQA2vyjgKOQEcsNDfURAMLHlFa9pHK7EEXEOlMKBcXvDGRnPeJ1LYulUbXNSA+I0nTfg/xHFpxmpw1an/AEj0WqspF8pFtR0vcTJ8Q4XzsIropLUjcgdOc0PwjZV8R4lhv/CMAP8A2W8oa+K/Fmmv0eo/Y9rpt0llNrzOovylxKlhOOi8FloniKNPEUmpVVDKw1Uzyvx54b4hw4Ni8F5mJwJJzWF2pdm7d56nnjMwbRtjpL2n186H8ev4eJQTPHvC/wCHuK4uyYvi/mYTBmx8vapUH/yPrPVcBgMHwrBJhOH0Fo0E2VR9e57yyz6D7QFarkpliZHqtbZqH8uv4OMFEzuJVL1Mi66bTy78SeOFW/wfD3BdVes5/pOyj7ntPQ8bX9pr67meK+KazY/xLjGpnNdxRW3YWP2Mt7RSp3eUlwjza8IJwinlwCk2GYk2lwrpCUqHk01pi1lFrCMy6ETq0QADBsCYcraRIvpARTYHnIESyVte8gyc4wKrCKFZb7RoCNvKeuh+kkF6kRIMo2uBCem22v2jGOii2o1GsXw+MQ6AXvzk6dFiRe5iACxzaL1k6WHBNze33lynQCi21/vAY6tlC0qRszbkchJaapWzUI/s8WWKuDkwdSvRoHIuZ36LtBjGMbA0D/q/tCYbDqeQBMOcNbkT3tN6G1U+OJcsxp7lbn4kMPiEZ7JmSp0bT6zpPD9TBeecQuHpUcWFKtUCAEg9x8Jzpwq2PKLC1G87KHIrIMysOY7zA3nafi3BmjotZ7eJdnqWHraa/OXEq6bzieE8eW4o4ghXttf7dRNpuL4ehh2xFesiUUF2cnQCcBdprK5+LRsLlZN/zIjU1A6Th8X+I3AMMLJiHrt0o0mI+ZtMRvxVU4tPL4Y38KPaZqn8w+4bD3X+Mkht+pn1A8ucUepZ7zM4jirXQHQd5h0fG3B8cqUsJi08+qbLTqelr9LG0q8Q4pSQOKbCrU7H0/OQrT2qWJRwRTvrgsyZHjnFEweHeq75couDPOuF4Mmo+LcEBifLV/at1Pczq8Txwrw6smK4Wr13BUFa2jDv0HzmQmdqaZ8rNbUptf8AadJtVLri8rki90Lfo8jC+g3kSN78oTY2C6xEX1yj5zYArN2F/fIWB0tLFRYFgRsIxAGUkW+UE6EfmlwC+jCDdCRptACiwMULUUiKAjbSxFpIKWNrbRU01A1+Etouw5bRjI0aItc6W+ksogG627yS01Vb30taxiJzEG0QDOLDXVRMfEk/x9QH8pAHym0QL5tAeVpkcUpmlihV/K4+omhtkoxv5KWvi5U8F3AgZwTOnxGBwacLSrTqK1Q+0vScdh62XnLoxj5LFjb3zpLK5SaaZhQmo5TQ2IspIWZhreXxLDna5YH/AEmHr4gakmZgLYjHK9v5dIEX7mUdzcY0PyL+2VO3URijUqVhiDlVAF/qtrDVBVag1BqrimwylSxtryjYSnmdQLm/ITWHDz5HmMVOY2yi9wZwtsXZLyZ9Droqqj4pHn/E+BNRf+VcA/lY8vfCUfDeLKCxpgnq/wCwnR8RAZddb+k9rQWAxDDAYlTbNQuAfftJ6Zt8SMvcdPCuPsiilwLhNOhVzXDkHWpzP7CdStFSmgmdw6mFpLYcp0PC8KcTWWmp1bSVXH2TyfOdRdZfc8sxMVQz8pj4im2Gcunsn2lE7bjPDv4KqaTWLcrc5y/EUUBgenKeo5rkKmdlFvfRXUipTDqPaFx7oit+sBw2qSKtMi+U3HYS4RcX5macXlZOxrn5wUiuRmBvygmW20sMvYH9JAiwJM9HorOL6wbaSwy63GloF7g2F9RyMAK1TbfnFHcWGg5x4COho0woG3eWFsuh+MArDcC19JMG+kYwuYAdRHsSfTykVUC99YVLC1r36RAMLkyFbCrXQ0nFw3zBhxoBpqe0kjWO1+UabTygazwc7XwuIwj6oXp8mXWC/iCRbKb89DOmsbW0IiWmpPsjvcbTSr3S6EcPkoT26qcs9HOUsFicUdFNNOdRhYfAc5dxWBTCYJBRucjXZuev95sOadNC9Q+ka3EogNiGuRYXuo5D+8oavVSt5mweqq2xKSWWVcA7o1wt7bGa+L4pUekoa9x0FhtvGo4fLsBJ1KOcWZQRMVymnwRr/rbnPMq1j/Tnq1W9wRcXkuEYZ62Exj7ecxC35gD94THYBL3u6pf1ZRczWw6UkpKKWlIAAASzp0nybL3ercavgsf1GXw+sVQLUsrLoQWE2sNjjRsyXvMfiGFqJWOIp8zdh+sCmL0kc63B8HGazSzptbS4NvHY+piDeo0xMZUGVvdGfFabynlrY1/Lw4JBOr8lnlRlNkOn09t0wnB6Zc1qg0UnKL9v+ZfKDYctLydDDJh6K0UHpXTue5jsMt9j7poxWFg7CuHhFRAMuU+orr3gXW7EfWWGXMOx5wZFvS3Paej2V2UXvrYwFRSLG9x2llwd+e14FttNRzgBTqnlzij1RztfXeKAjfRiRdrawwCkkgyuh5/SFDcr6AbmMYa1r7cjCjU9NYJG1Gb6Qid2X5xAEUkn1NfkLR7BtALn79o6KqWJBB5CEVTyWADZGGlwR2EmKa5t7m2okgQ6nMLgQgSwKga/l7wAzOKn1UqK7HUw+DojSV+JjLjaZI0K6HrrLmEYaTPvlmw5HdpOWpaf6NbCYFq49K39wgsXgzRJDTV4JxOngySy302lLi+OXEVWfrE4rGSvOFSqynyc/jKYymUOG1iMScM21sw7df0l3F1QQenOZWAbPxcNbQIxI6DSOj7lvZ5NXcdGy12N7aSpWwNGsxJT1cztLxtmvqp3Eg65jdt+Rl7GTqXFS7RlHhlAHVST3JsZcRFp07IgQDkNrQrqoDCop0PXeMF9OmgO0EsAoqPSBlQBex1kLXBIW+WFJFiutjvAuSCoYC89HoE4CPdWse40g2BJ2uTCsL6W3g6gvtsPrAAFSxB0y9idJXb2tbaaWlmoRmOUWPcSvVAXfcwAp4gWGux6RRsQ99BYRoCNqmSpllPUR+u8oUiwW172Nx3lxWu4IB2jGWlGhsDpvCoNAdQDvK6VLEE2sbywGYqABtY3iAOgA0ze8dJK9hv0+Erh7nT2hyhNCBa8AC72GgJFyYSm2mpCnfXYwSsDsfn95K90IuL9YAVeKYdqlFayMGanrYHccxKuExXpU33mub2BvmtvMfHcPqK7VcLcm92QfpK11Pl8kY+46D3/ADh2XRjLDQmCqYgvcAzFOKNNstVGU9G0kTjXq+ikrMf6UFz8hKnjPODA/BuzjBaxmIAGUH/MYfgGGzLUxjXBqCyf5Rz+cr4Phj4lw2M/l02PsbE+/pOhRVopY+ym3KW6anHlnRbdovQvOXZELcEHfeQC3HtDKRe5htGubknpBM1r5bA9Wlk1QTi/tKO3eQykHkO8lU6g3PO+0gGGoaxuNIAMTfLtfqYBx6tBtt2hLm1jbsQIJmv6TpbW8AIVNvTcnp0gXa4swEk76qCdRuBA1KhvY2IPKAAqht7R/sJWqN/u8LUezFXPIaiV67AjbXrACriDYjWKBxDa3H0jwEaqVCGHulpKhXe5BuDrFFGAZHstyL2llanpvYaxRQAIH9TKL6CTDmyHrtFFAAqVPWEtoevKTYC4NhZo8UQD+YSMo05fKIsVHpPvjxQAFWG+YBjtqJFKQC+j0hjsIooYEFDEZ1G6W3Ohkkqk3zXzWte8UUBjqchY8gbAQNTSmdL2iigBAsctxYDa1oFzkcAbmKKAA2exuOe8EfUhKkjlFFA9SWMAKrZDbc9ZWZiWuORtFFA8gKrmxJ6ypUYkbDWKKAFN7q2/K8aKKAH/2Q==

**Comment by wodk-moment** [comment]
3D Ballz

**Comment by wodk-moment** [comment]
Reopened due to [4581dbb](https://github.com/CIA-Puppygirl/poopballs/commit/4581dbbdf9e65b585f3954f0b0fa853f3653d901)

**Comment by wodk-moment** [comment]
This issue is not resolved. Please take this seriously, CIA-Puppygirl.
