### ISSUE TITLE
Fake Repo

### ISSUE THREAD

**Issue by transgramsci** [CIA-Puppygirl/poopballs#6]
This repository is not real, your code is mediocre and it doesn't even work close to how you'd imagine it would. Take for instance the incredible fact that the LUA script is not even formatted in LUA syntax, anyone should be able to see that. Secondly as a member of a serious organization which absolutely generates many serious code bases all the time, you are misleading people. For this reason I believe you should delete your account and never code again. -Gram

**Comment by pr1ncess-emily** [comment]
this issue fake and gay
@CIA-Puppygirl please close this issue

**Comment by wodk-moment** [comment]
You're white.

**Comment by transgramsci** [comment]
reopen my issue

**Comment by pr1ncess-emily** [comment]
no you stupid  binch
